window.DASHBOARD_DATA = {
  "total": 3594,
  "bairros": {
    "CENTRO": 345,
    "CATALAO": 145,
    "SANTA ROSA": 135,
    "BOM PASTOR": 126,
    "SAO JOSE": 97,
    "INTERLAGOS": 88,
    "NOSSA SENHORA DAS GRACAS": 87,
    "BELVEDERE": 81,
    "MANOEL VALINHAS": 80,
    "PORTO VELHO": 75,
    "JARDINOPOLIS": 70,
    "SERRA VERDE": 69,
    "SANTO ANTONIO DOS CAMPOS": 60,
    "SANTO ANTONIO": 54,
    "PADRE EUSTAQUIO": 53,
    "CHANADOUR": 52,
    "SANTA LUCIA": 51,
    "VILA BELO HORIZONTE": 50,
    "PARAISO": 50,
    "JOAO ANTONIO GONCALVES": 49,
    "DANILO PASSOS": 48,
    "JARDIM CANDELARIA": 46,
    "ICARAI": 42,
    "SANTA CLARA": 41,
    "PLANALTO": 39,
    "TIETE": 38,
    "ORION": 37,
    "ESPLANADA": 36,
    "JARDIM DAS ACACIAS": 34,
    "IPIRANGA": 34,
    "NITEROI": 33,
    "SAO SEBASTIAO": 33,
    "JARDIM NOVA AMERICA": 32,
    "DAS OLIVEIRAS": 31,
    "SAO LUIS": 31,
    "AFONSO PENA": 30,
    "LEVINDO PAULA PEREIRA": 28,
    "MARIA HELENA": 28,
    "SAO JOAO DE DEUS": 28,
    "LIBERDADE": 27,
    "VILA ROMANA": 27,
    "ALVORADA": 26,
    "VALE DO SOL": 26,
    "CIDADE JARDIM": 26,
    "SANTA TEREZA": 24,
    "BELA VISTA": 23,
    "MANGABEIRAS": 22,
    "JARDIM CANDIDES": 22,
    "RANCHO ALEGRE": 22,
    "CASA NOVA": 21
  },
  "cnae": {
    "Obras de alvenaria": 969,
    "Instalação e manutenção elétrica": 606,
    "Serviços de pintura de edifícios em geral": 397,
    "Incorporação de empreendimentos imobiliários": 309,
    "Serviços de engenharia": 260,
    "Construção de edifícios": 228,
    "Obras de acabamento em gesso e estuque": 107,
    "Instalações hidráulicas sanitárias e de gás": 105,
    "Outras obras de acabamento da construção": 102,
    "Instalação e manutenção de sistemas centrais de ar condicionado de ventilação e refrigeração": 100,
    "Serviços especializados para construção não especificados anteriormente": 58,
    "Serviços de arquitetura": 51,
    "Instalação de portas janelas tetos divisórias e armários embutidos de qualquer material": 48,
    "Aplicação de revestimentos e de resinas em interiores e exteriores": 34,
    "Montagem e desmontagem de andaimes e outras estruturas temporárias": 21,
    "Obras de terraplenagem": 20,
    "Instalação de painéis publicitários": 20,
    "Instalações de sistema de prevenção contra incêndio": 18,
    "Outras obras de instalações em construções não especificadas anteriormente": 14,
    "Instalação manutenção e reparação de elevadores escadas e esteiras rolantes": 14,
    "Administração de obras": 13,
    "Montagem de estruturas metálicas": 12,
    "Construção de estações e redes de distribuição de energia elétrica": 12,
    "Perfuração e construção de poços de água": 11,
    "Tratamentos térmicos acústicos ou de vibração": 11,
    "Construção de redes de abastecimento de água coleta de esgoto e construções correlatas exceto obras de irrigação": 9,
    "Obras de urbanização - ruas praças e calçadas": 9,
    "Obras de fundações": 6,
    "Manutenção de estações e redes de telecomunicações": 6,
    "Impermeabilização em obras de engenharia civil": 4,
    "Serviços de operação e fornecimento de equipamentos para transporte e elevação de cargas e pessoas para uso em obras": 4,
    "Obras de montagem industrial": 4,
    "Perfurações e sondagens": 3,
    "Outras obras de engenharia civil não especificadas anteriormente": 2,
    "Construção de estações e redes de telecomunicações": 2,
    "Manutenção de redes de distribuição de energia elétrica": 2,
    "Montagem e instalação de sistemas e equipamentos de iluminação e sinalização em vias públicas portos e aeroportos": 1,
    "Construção de obras de arte especiais": 1,
    "Obras portuárias marítimas e fluviais": 1
  },
  "porte": {
    "MEDIO/GRANDE PORTE": 161,
    "MICRO EMPRESA": 3253,
    "EMPRESA DE PEQUENO PORTE": 180
  },
  "tempoAbertura": {
    "Até 1 ano": 621,
    "1-3 anos": 750,
    "3-5 anos": 536,
    "5-10 anos": 1009,
    "Acima de 10 anos": 678
  },
  "capitalSocial": {
    "total": 4324279814,
    "ranges": {
      "Até 10k": 2632,
      "10k - 50k": 411,
      "50k - 100k": 210,
      "100k - 500k": 226,
      "Acima de 500k": 115
    }
  },
  "faturamento": {
    "R$ 4.800.001,00 a R$ 20.000.000,00": 144,
    "R$ 1,00 a R$ 81.000,00": 2120,
    "R$ 360.001,00 a R$ 4.800.000,00": 180,
    "R$ 50.000.000,00 a R$ 10.000.000.000,00": 17,
    "R$ 81.001,00 a R$ 3.600.000,00": 1133
  },
  "colaboradores": {
    "100 A 500 COLABORADORES": 144,
    "1 A 2 COLABORADORES": 2120,
    "20 A 99 COLABORADORES": 180,
    "ACIMA DE 700 COLABORADORES": 17,
    "3 A 9 COLABORADORES": 1133
  },
  "faixaEtaria": {
    "41 A 50 ANOS": 548,
    "31 A 40 ANOS": 508,
    "21 A 30 ANOS": 140,
    "51 A 60 ANOS": 283,
    "71 A 80 ANOS": 89,
    "61 A 70 ANOS": 201,
    "13 A 20 ANOS": 7,
    "ACIMA 80 ANOS": 38
  }
};